TOKEN = '5022055945:AAHi8AeCngN78T-61e1ODuLlo3BnfOxtRhg'  # bot token from @BotFather
way_to_list = 'C:\\Users\\User\\PycharmProjects\\Telegram_bot\\Exel_file\\List.xlsx'
club1 = 'Клуб1'
club1_description = 'Интересный клуб, где играют в тенис'
club2 = 'Клуб2'
club2_description = 'Интересный клуб, где играют в го'
club3 = 'Клуб3'
club3_description = 'Интересный клуб, где люди просто спят'
d_list = []
chat_id = {}
